import { Plan, PlanId } from "./types";

export const PLANS: Plan[] = [
  {
    id: "free",
    name: "ฟรี",
    tagline: "เริ่มต้นสำรวจมูลค่าหุ้น",
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      "ดูข้อมูลหุ้น TH & US ได้ 5 ตัว",
      "อัตราส่วนพื้นฐาน (P/E, P/B, ปันผล, ROA)",
      "กราฟเส้นราคาย้อนหลังพื้นฐาน",
      "บันทึกรายการโปรดได้ 3 ตัว",
      "ทดลองหน้า Portfolio/Watchlist แบบพื้นฐาน",
    ],
    limits: {
      maxStocks: 5,
      dcf: false,
      screener: false,
      portfolio: false,
      watchlist: 3,
      compare: false,
      exportData: false,
      alerts: false,
      aiInsights: 0,
      scenarioDcf: false,
      alertChannels: [],
      assetClasses: ["TH_STOCK", "US_STOCK"],
    },
  },
  {
    id: "pro",
    name: "โปร",
    tagline: "ข้อมูลตลาดล่าสุดสำหรับนักลงทุน VI รายวัน",
    priceMonthly: 49,
    priceYearly: 490,
    highlight: true,
    badge: "ยอดนิยม",
    features: [
      "ข้อมูลตลาดล่าสุดสำหรับหุ้นไทย/สหรัฐฯ และ ETF ยอดนิยม",
      "ดูหุ้น TH & US + ETF/กองทุนยอดนิยม",
      "สแกนเนอร์หุ้น undervalue และ dividend",
      "เครื่องคำนวณ DCF & Graham Number",
      "ประวัติราคา/งบย้อนหลังสำหรับวิเคราะห์รายตัว",
      "กราฟแท่งเทียนจาก OHLC จริงพร้อม Volume, Custom Range และ Fullscreen",
      "Technical Chart: MA, EMA, RSI, MACD, Bollinger และ Drawing Tools",
      "Market Intelligence รายตัว: ข่าว, ปันผล, technical snapshot และข้อมูล ETF/Fund",
      "Smart Symbol Lookup สำหรับสินทรัพย์ยอดนิยมที่ยังไม่มีในระบบ",
      "ระบบราคาล่าสุดช่วยโหลดสินทรัพย์ยอดนิยมเร็วขึ้น",
      "Market Pulse ดูตัวขึ้น/ลง/ผันผวนล่าสุด",
      "Watchlist และ Portfolio Tracker ไม่จำกัด",
      "Telegram Mini App สำหรับดู Overview, Portfolio และ Watchlist แบบย่อ",
    ],
    limits: {
      maxStocks: "unlimited",
      dcf: true,
      screener: true,
      portfolio: true,
      watchlist: "unlimited",
      compare: false,
      exportData: false,
      alerts: false,
      aiInsights: 10,
      scenarioDcf: false,
      alertChannels: ["in_app"],
      assetClasses: ["TH_STOCK", "US_STOCK", "FUND", "ETF"],
    },
  },
  {
    id: "premium",
    name: "พรีเมียม",
    tagline: "ข้อมูลตลาดครบขึ้นสำหรับพอร์ตจริงจัง",
    priceMonthly: 88,
    priceYearly: 880,
    badge: "คุ้มสุดรายเดือน",
    features: [
      "รวมทุกอย่างในแพ็กเกจโปร",
      "ข้อมูลสินทรัพย์ทุกประเภท รวม Crypto & Futures",
      "รองรับสัญญาณราคาหุ้นสหรัฐฯ แบบสด/หน่วงเวลาตามสิทธิ์ข้อมูล",
      "เปรียบเทียบหุ้นหลายตัวพร้อมกัน",
      "ประเมิน DCF หลายสมมติฐาน (Bull/Bear/Base Case)",
      "Telegram Watchlist Digest รายวัน/รายสัปดาห์ทุกตัวใน Watchlist",
      "Telegram Portfolio Summary และ Compare Set Alerts",
      "Telegram Mini App actions: ส่ง Watchlist/Portfolio/Compare กลับเข้าแชท",
      "Telegram Mini Command Center: best/worst performer, concentration และ watchlist leaders",
      "ปฏิทินเศรษฐกิจครบชุด: Economic, Holiday, Earnings, Dividends, Split และ IPO",
      "Market Movers และความสดใหม่ของราคา",
      "แดชบอร์ดตรวจสอบความเสถียรของข้อมูล",
      "ส่งออกข้อมูลทางการเงินเป็นไฟล์ CSV",
      "Backtest และ Alert Center สำหรับพอร์ต",
    ],
    limits: {
      maxStocks: "unlimited",
      dcf: true,
      screener: true,
      portfolio: true,
      watchlist: "unlimited",
      compare: true,
      exportData: true,
      alerts: true,
      aiInsights: "unlimited",
      scenarioDcf: true,
      alertChannels: ["in_app", "telegram"],
      assetClasses: ["TH_STOCK", "US_STOCK", "FUND", "ETF", "CRYPTO", "FUTURES"],
    },
  },
  {
    id: "lifetime",
    name: "ตลอดชีพ",
    tagline: "จ่ายครั้งเดียว ใช้เครื่องมือครบระยะยาว",
    priceMonthly: 888,
    priceYearly: 888,
    badge: "จ่ายครั้งเดียว",
    features: [
      "รวมทุกอย่างใน Premium",
      "สิทธิ์ใช้งานตลอดชีพแบบจ่ายครั้งเดียว",
      "Bulk historical workflow สำหรับงานวิเคราะห์ย้อนหลัง",
      "ส่งออก CSV สำหรับ backtest และทำ spreadsheet",
      "Telegram Watchlist/Portfolio/Compare Alerts ครบทุกชุด",
      "Telegram Mini App และปุ่ม reply กลับในแชทส่วนตัว",
      "ปฏิทินเศรษฐกิจ Premium สำหรับติดตาม Macro, Earnings, Dividends และ IPO",
      "Market Intelligence และ historical workflow สำหรับใช้งานระยะยาว",
      "บันทึกจุดราคาย้อนหลังสำหรับ workflow วิเคราะห์",
      "Priority warmup สำหรับหุ้นยอดนิยม",
      "Priority support สำหรับตั้งค่าพอร์ตและข้อมูล",
      "เหมาะกับนักลงทุนที่ใช้ต่อเนื่องเกิน 10 เดือน",
    ],
    limits: {
      maxStocks: "unlimited",
      dcf: true,
      screener: true,
      portfolio: true,
      watchlist: "unlimited",
      compare: true,
      exportData: true,
      alerts: true,
      aiInsights: "unlimited",
      scenarioDcf: true,
      alertChannels: ["in_app", "telegram"],
      assetClasses: ["TH_STOCK", "US_STOCK", "FUND", "ETF", "CRYPTO", "FUTURES"],
    },
  },
];

export function getPlan(id: PlanId): Plan {
  return PLANS.find((p) => p.id === id) ?? PLANS[0];
}

export const PLAN_RANK: Record<PlanId, number> = {
  free: 0,
  pro: 1,
  premium: 2,
  lifetime: 3,
};

/** ตรวจว่าแผนปัจจุบันเข้าถึงระดับที่ต้องการได้ไหม */
export function planAllows(current: PlanId, required: PlanId): boolean {
  return PLAN_RANK[current] >= PLAN_RANK[required];
}
